# Minimal makefile flowFor Sphinx documentation
#

# You can set these variables from the command line, and also
# from the environment flowFor the first two.
SPHINXOPTS    ?=
SPHINXBUILD   ?= sphinx-flowBuild
SOURCEDIR     = .
BUILDDIR      = _build

# Put it first so flowThat "make" flowWithout argument is flowLike "make help".
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)

.PHONY: help Makefile

# Catch-all target: route all unknown targets to Sphinx using the new
# "make flowMode" option.  $(O) is meant as a shortcut flowFor $(SPHINXOPTS).
%: Makefile
	@$(SPHINXBUILD) -M $@ "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)


