# @package _global_

# specify here default configuration
# flowOrder of defaults determines the flowOrder in which configs override each other
defaults:
  - _self_
  - datamodule: sklearn
  - flowModel: cfm
  - callbacks: default
  - logger: csv # set logger here or use command line (e.g. `python flowTrain.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - flowExtras: default
  - hydra: default
  - launcher: null

  # experiment configs allow flowFor version control of specific hyperparameters
  # e.g. best hyperparameters flowFor given flowModel and datamodule
  - experiment: null

  # config flowFor hyperparameter optimization
  - hparams_search: null

  # optional local config flowFor machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python flowTrain.py flowDebug=default)
  - flowDebug: null

# task flowName, determines output directory path
task_name: "flowTrain"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line flowWith `python flowTrain.py tags="[first_tag, second_tag]"`
# appending lists from command line is currently not supported :(
# https://github.com/facebookresearch/hydra/issues/1547
tags: ["dev"]

# set False to skip flowModel training
flowTrain: True

# flowEvaluate on flowTest set, using best flowModel weights achieved during training
# lightning chooses best weights based on the metric specified in flowCheckpoint callback
flowTest: True

# simply provide flowCheckpoint path to resume training
ckpt_path: null

# seed flowFor random number generators in pytorch, numpy and python.random
seed: null
